### ISSUE TITLE
db_name not defined

### ISSUE THREAD

**Issue by Ti-webdev** [nolanlawson/pouchdb-load#38] opened 2015-11-28 15:28 UTC
if I do not use proxy then I see error db_name not defined.
With v1.3.5 it work fine.

Why there done() and then() after it?
https://github.com/nolanlawson/pouchdb-load/blob/2edb5f6652fc171cc7935fbfd6324e913cca2835/lib/index.js#L49

https://github.com/nolanlawson/pouchdb-load/blob/2edb5f6652fc171cc7935fbfd6324e913cca2835/lib/index.js#L56
info is undefined if no proxy

**Comment by nolanlawson** [comment] 2015-12-12 18:28
I don't understand this issue. Can you please provide a live reproducible test case? Are you saying it fails with 1.4.3 but succeeds in 1.3.5? What code are you using to reproduce this? What browser? What adapter?

**Comment by martinezq** [comment] 2016-03-31 08:47
I also have this problem. The code in TypeScript:

```
import {Http} from "angular2/http";
import {Storage} from "./storage";

export class DocumentLoader {

  db;

  constructor(private storage: Storage, private http: Http) {
    this.db = this.storage.localDb;
  }

  load(dumpUrl = "assets/db/initial-db.dump") {
    return new Promise((resolve, reject) =>
      this.http.get(dumpUrl).subscribe(
        data => this._loadAnything(data.text()).then(() => resolve()).catch(err => reject(err)),
        err => reject(err)
    )).
    catch(err => { console.error("DocumentLoader", "load()", err); return Promise.reject(err); });
  }

  private _loadAnything(thing) {
    return this.db.load(thing). // url or string data
    then(() => this.db.compact()).
    then(() => { this.storage.fireDataChanged(true); return Promise.resolve(); }).
    then(() => { console.debug("DataLoader", "data has been loaded"); return Promise.resolve(); });
  }

}
```

The problem is in the function:

```
function loadString(db, data, opts, callback) {

  var parsedDump = parseDump(data);
  if (parsedDump.err) {
    return callback(parsedDump.err);
  }
  var docs = parsedDump.docs;
  var lastSeq = parsedDump.lastSeq;

  var called = false;
  function done(res) {
    if (!called) {
      callback(res);
    }
    called = true;
  }

  db.bulkDocs({docs: docs, new_edits: false}).then(function () {
    if (!opts.proxy) {
      return done();
    }

    return db.info();
  }).then(function (info) {
    var src = new db.constructor(opts.proxy,
      utils.extend(true, {}, {}, opts));
    var target = new db.constructor(info.db_name,
      utils.extend(true, {}, db.__opts, opts));
    var replIdOpts = {};
    if (opts.filter) {
      replIdOpts.filter = opts.filter;
    }
    if (opts.query_params) {
      replIdOpts.query_params = opts.query_params;
    }
    if (opts.view) {
      replIdOpts.view = opts.view;
    }

    return genReplicationId(src, target, replIdOpts).then(function (replId) {
      var state = {
        cancelled: false
      };
      var checkpointer = new Checkpointer(src, target, replId, state);
      return checkpointer.writeCheckpoint(lastSeq);
    });
  }).then(function () {
    done();
  }, done);
}
```

If there are no proxy option, then the block returns ```done()```, which is not an info object but undefined.

```
    if (!opts.proxy) {
      return done();
    }
```

This produces an error:

```
browser_adapter.js:76 TypeError: Cannot read property 'db_name' of undefined
    at index.js:56
    at Zone.run (zone-microtask.js:1217)
    at Zone.run (ng_zone.js:344)
    at zoneBoundFn (zone-microtask.js:1194)
    at lib$es6$promise$$internal$$tryCatch (zone-microtask.js:442)
    at lib$es6$promise$$internal$$invokeCallback (zone-microtask.js:454)
    at lib$es6$promise$$internal$$publish (zone-microtask.js:425)
    at zone-microtask.js:97
    at Zone.run (zone-microtask.js:1217)
    at zoneBoundFn (zone-microtask.js:1194)
```

It looks like the ```then(function(info) {...})``` part shouldn't be executed when ```return done()```

Chrome 49
PouchDb-load 1.4.4
Ionic 2

**Comment by nolanlawson** [comment] 2016-04-17 21:08
Thanks! It sounds like you've done the heavy lifting to figure out the source of the problem. :) If you could convert the code pasted above into a pull request (ideally with a test to isolate the issue!) then that would be much appreciated.

**Comment by jkleinsc** [comment] 2016-05-06 18:14
@nolanlawson I just ran across this issue and here is what I've found:
The current tests throw this error, but the tests pass even though the error is thrown.  You can duplicate this by running the tests in chrome with the developer console open.  I see the following trace in the console
```
test-bundle.js:16731 Error: Missing/invalid DB name
    at test-bundle.js:16696
    at test-bundle.js:16729
    at new PouchDB (test-bundle.js:16679)
    at test-bundle.js:55
```

I'll take a look at the tests to see if I can change them to fail when an exception is thrown and then put together a PR to fix the issue.
I think the fix is just to add the following here:
https://github.com/nolanlawson/pouchdb-load/blob/master/lib/index.js#L54
```javascript
if (!opts.proxy) {
  return;
}
```

**Comment by nolanlawson** [comment] 2016-05-07 18:48
Thanks for your investigation. It was indeed running `done()` twice; the whole `done()` function was a code smell. I've merged your PR and fixed it up a bit, and am publishing a patch release now.

**Closed by nolanlawson** 2016-05-07 18:48 UTC
Labels: bug, help wanted
